import fs from 'fs/promises';
import { readFileSync } from 'fs';
import path from 'path';
import os from 'os';

/**
 * Environment / settings helpers for the Smyth setup wizard.
 * Reads/writes a user-scoped `.env` and `settings.json` outside the app bundle.
 */

export function getUserDataDir(): string {
  const base =
    process.env.SMYTH_USER_DATA ??
    (process.platform === 'darwin'
      ? path.join(os.homedir(), 'Library', 'Application Support', 'smyth')
      : path.join(os.homedir(), '.smyth'));
  return base;
}

export function getEnvPath(): string {
  return process.env.SMYTH_ENV_PATH ?? path.join(getUserDataDir(), /*turbopackIgnore: true*/ '.env');
}

export function getSettingsPath(): string {
  return path.join(getUserDataDir(), 'settings.json');
}

export interface SmythSettings {
  setupComplete: boolean;
  workspacePath: string;
  permissions: Record<string, boolean | 'deferred'>;
  providers: Record<string, ProviderSetting>;
  lastUpdated: string;
}

export interface ProviderSetting {
  enabled: boolean;
  model?: string;
  endpoint?: string;
  keyName?: string;
  hasKey?: boolean;
  setup?: Record<string, any>;
}

export const DEFAULT_SETTINGS: SmythSettings = {
  setupComplete: false,
  workspacePath: path.join(os.homedir(), 'Library', 'Application Support', 'smyth', 'workspace'),
  permissions: {},
  providers: {},
  lastUpdated: new Date().toISOString(),
};

/**
 * Resolve the bounded workspace directory — the one place the agent may
 * read/write files. Order of precedence:
 *   1. `SMYTH_WORKSPACE` env (explicit override)
 *   2. `settings.json` workspacePath (what the user picked in setup)
 *   3. a safe per-user default (NOT `/` and NOT the whole home dir)
 *
 * This is synchronous so it can back the module-level constants used across
 * the API routes and tool layer without async plumbing.
 */
export function getWorkspacePath(): string {
  if (process.env.SMYTH_WORKSPACE) return process.env.SMYTH_WORKSPACE;
  try {
    const raw = readFileSync(getSettingsPath(), 'utf-8');
    const parsed = JSON.parse(raw);
    if (typeof parsed.workspacePath === 'string' && parsed.workspacePath.trim()) {
      return parsed.workspacePath;
    }
  } catch {
    /* no settings yet — fall through to default */
  }
  return DEFAULT_SETTINGS.workspacePath;
}

export async function ensureUserDataDir(): Promise<void> {
  const dir = getUserDataDir();
  await fs.mkdir(dir, { recursive: true });
}

export async function readSettings(): Promise<SmythSettings> {
  const settingsPath = getSettingsPath();
  try {
    const raw = await fs.readFile(settingsPath, 'utf-8');
    const parsed = JSON.parse(raw);
    return { ...DEFAULT_SETTINGS, ...parsed };
  } catch {
    return { ...DEFAULT_SETTINGS };
  }
}

export async function writeSettings(settings: Partial<SmythSettings>): Promise<SmythSettings> {
  await ensureUserDataDir();
  const existing = await readSettings();
  const merged: SmythSettings = {
    ...existing,
    ...settings,
    lastUpdated: new Date().toISOString(),
  };
  await fs.writeFile(getSettingsPath(), JSON.stringify(merged, null, 2), 'utf-8');
  return merged;
}

export async function readEnvFile(): Promise<Record<string, string>> {
  const envPath = getEnvPath();
  try {
    const raw = await fs.readFile(/*turbopackIgnore: true*/ envPath, 'utf-8');
    const out: Record<string, string> = {};
    for (const line of raw.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const idx = trimmed.indexOf('=');
      if (idx === -1) continue;
      const key = trimmed.slice(0, idx).trim();
      let value = trimmed.slice(idx + 1).trim();
      if (value.startsWith('"') && value.endsWith('"')) {
        value = value.slice(1, -1).replace(/\\n/g, '\n').replace(/\\"/g, '"').replace(/\\\\/g, '\\');
      } else if (value.startsWith("'") && value.endsWith("'")) {
        value = value.slice(1, -1);
      }
      out[key] = value;
    }
    return out;
  } catch {
    return {};
  }
}

export async function writeEnvFile(env: Record<string, string>): Promise<void> {
  await ensureUserDataDir();
  const envPath = getEnvPath();
  const existing = await readEnvFile();
  const merged = { ...existing, ...env };
  const lines = Object.entries(merged).map(([k, v]) => {
    const escaped = String(v).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
    return `${k}="${escaped}"`;
  });
  const content = `# Smyth runtime environment\n# Generated by setup wizard on ${new Date().toISOString()}\n\n${lines.join('\n')}\n`;
  await fs.writeFile(/*turbopackIgnore: true*/ envPath, content, 'utf-8');
}

export async function loadRuntimeEnv(): Promise<Record<string, string>> {
  const envPath = getEnvPath();
  try {
    const raw = await fs.readFile(/*turbopackIgnore: true*/ envPath, 'utf-8');
    return parseEnvText(raw);
  } catch {
    return {};
  }
}

export function parseEnvText(raw: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of raw.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx === -1) continue;
    const key = trimmed.slice(0, idx).trim();
    let value = trimmed.slice(idx + 1).trim();
    if (value.startsWith('"') && value.endsWith('"')) {
      value = value.slice(1, -1).replace(/\\n/g, '\n').replace(/\\"/g, '"').replace(/\\\\/g, '\\');
    } else if (value.startsWith("'") && value.endsWith("'")) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}
