const { spawn } = require('child_process');
const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { PORTS, HEALTH, SHUTDOWN, getPaths } = require('./constants');

let smythProcess = null;
let omnirouteProcess = null;
let omniroutePort = null;

function findFreePort(startPort) {
  return new Promise((resolve, reject) => {
    const net = require('net');
    const server = net.createServer();
    server.unref();
    server.on('error', (err) => {
      // EADDRINUSE → try the next port
      if (err.code === 'EADDRINUSE') {
        findFreePort(startPort + 1).then(resolve, reject);
        return;
      }
      reject(err);
    });
    // Bind on all interfaces; OmniRoute binds 0.0.0.0, so we must test the same.
    server.listen(startPort, '0.0.0.0', () => {
      const { port } = server.address();
      server.close(() => resolve(port));
    });
  });
}

function healthCheck(url, timeoutMs = HEALTH.TIMEOUT_MS) {
  return new Promise((resolve) => {
    const start = Date.now();
    function poll() {
      if (Date.now() - start > timeoutMs) {
        return resolve(false);
      }
      const req = http.get(url, (res) => {
        if (res.statusCode >= 200 && res.statusCode < 400) {
          res.resume();
          return resolve(true);
        }
        res.resume();
        setTimeout(poll, HEALTH.POLL_INTERVAL_MS);
      });
      req.on('error', () => {
        setTimeout(poll, HEALTH.POLL_INTERVAL_MS);
      });
      req.setTimeout(2000, () => {
        req.destroy();
        setTimeout(poll, HEALTH.POLL_INTERVAL_MS);
      });
    }
    poll();
  });
}

async function healthCheckWithRetry(url) {
  for (let i = 0; i < HEALTH.RETRY_CYCLES; i++) {
    const ok = await healthCheck(url);
    if (ok) return true;
    if (i < HEALTH.RETRY_CYCLES - 1) {
      await new Promise((r) => setTimeout(r, HEALTH.RETRY_BACKOFF_MS));
    }
  }
  return false;
}

function logCrash(serverName, error) {
  try {
    const paths = getPaths();
    fs.mkdirSync(paths.logs, { recursive: true });
    const crashFile = path.join(paths.logs, `crash-${Date.now()}.json`);
    fs.writeFileSync(
      crashFile,
      JSON.stringify(
        {
          server: serverName,
          timestamp: new Date().toISOString(),
          error: error?.message || String(error),
          stack: error?.stack,
        },
        null,
        2
      )
    );
  } catch {
    // best-effort logging
  }
}

function spawnSmyth() {
  const paths = getPaths();
  const env = {
    ...process.env,
    NODE_ENV: 'production',
    PORT: String(PORTS.SMYTH),
    SMYTH_USER_DATA: paths.smythUserData,
    SMYTH_ENV_PATH: paths.envFile,
    SMYTH_CHROMIUM_PATH: paths.chromium,
    NODE_OPTIONS: '--max-old-space-size=4096',
    // process.execPath is the Electron binary; this flag makes it behave as
    // plain Node so it can run server.js as a child process.
    ELECTRON_RUN_AS_NODE: '1',
  };

  smythProcess = spawn(process.execPath, [paths.smythServer], {
    env,
    stdio: ['ignore', 'pipe', 'pipe'],
  });

  smythProcess.stdout?.on('data', (d) => process.stdout.write(`[smyth] ${d}`));
  smythProcess.stderr?.on('data', (d) => process.stderr.write(`[smyth:err] ${d}`));

  smythProcess.on('error', (err) => logCrash('smyth', err));
  smythProcess.on('exit', (code, signal) => {
    if (code !== 0 && signal !== 'SIGTERM') {
      logCrash('smyth', new Error(`exit code ${code} signal ${signal}`));
    }
  });

  return smythProcess;
}

function generateSecret(length = 48) {
  return crypto.randomBytes(length).toString('base64url');
}

function loadEnvPairs(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const raw = fs.readFileSync(filePath, 'utf8');
  const out = {};
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx === -1) continue;
    const key = trimmed.slice(0, idx).trim();
    const value = trimmed.slice(idx + 1).trim();
    if (key) out[key] = value;
  }
  return out;
}

function ensureOmnirouteDataDir() {
  const paths = getPaths();
  fs.mkdirSync(paths.omnirouteDataDir, { recursive: true });

  if (!fs.existsSync(paths.omnirouteEnvFile)) {
    // Persist per-app-instance secrets. OmniRoute's CLI provisions some
    // automatically on first run, but generating them here guarantees they
    // are tied to this application instance and not to any other install.
    const env = [
      '# Auto-generated by Smyth — per-instance OmniRoute environment.',
      `STORAGE_ENCRYPTION_KEY=${generateSecret(64)}`,
      `API_KEY_SECRET=${generateSecret(64)}`,
      `JWT_SECRET=${generateSecret(64)}`,
      'INITIAL_PASSWORD=',
      '',
    ].join('\n');
    fs.writeFileSync(paths.omnirouteEnvFile, env, { encoding: 'utf8', mode: 0o600 });
  }
}

async function spawnOmniroute() {
  const paths = getPaths();
  const omnirouteCli = paths.omnirouteCli;

  if (!omnirouteCli) {
    throw new Error(
      'OmniRoute CLI not found. Please install OmniRoute and ensure `omniroute` is available in PATH, ' +
        'or set OMNIROUTE_CLI to the binary location.'
    );
  }

  omniroutePort = await findFreePort(PORTS.OMNIROUTE_START);
  ensureOmnirouteDataDir();

  // Explicitly apply the per-instance .env values so the OmniRoute CLI's own
  // dotenv loader (which reads ~/.omniroute/.env and the package .env) cannot
  // overwrite them — dotenv does not replace already-set variables.
  const instanceEnv = loadEnvPairs(paths.omnirouteEnvFile);

  const env = {
    ...process.env,
    NODE_ENV: 'production',
    DATA_DIR: paths.omnirouteDataDir,
    OMNIROUTE_BASE_URL: `http://127.0.0.1:${omniroutePort}`,
    PORT: String(omniroutePort),
    NODE_OPTIONS: '--max-old-space-size=4096',
    ...instanceEnv,
  };

  // Use --no-tray / --no-open so the CLI does not try to pop up its own UI.
  const args = ['serve', '--port', String(omniroutePort), '--no-tray', '--no-open'];

  omnirouteProcess = spawn(omnirouteCli, args, {
    env,
    cwd: paths.omnirouteDataDir,
    stdio: ['ignore', 'pipe', 'pipe'],
  });

  omnirouteProcess.stdout?.on('data', (d) => process.stdout.write(`[omniroute] ${d}`));
  omnirouteProcess.stderr?.on('data', (d) => process.stderr.write(`[omniroute:err] ${d}`));

  omnirouteProcess.on('error', (err) => logCrash('omniroute', err));
  omnirouteProcess.on('exit', (code, signal) => {
    if (code !== 0 && signal !== 'SIGTERM') {
      logCrash('omniroute', new Error(`exit code ${code} signal ${signal}`));
    }
  });

  return omnirouteProcess;
}

async function startAll() {
  // In dev mode, next dev is already serving on port 3000 — skip spawning Smyth
  const isDev = process.env.SMYTH_DEV === '1' || process.env.NODE_ENV === 'development';
  if (!isDev) {
    spawnSmyth();
  } else {
    console.log('[server-manager] Dev mode: skipping Smyth spawn (next dev already running)');
  }
  await spawnOmniroute();

  const smythOk = await healthCheckWithRetry(HEALTH.SMYTH_URL);
  const omnirouteUrl = `http://127.0.0.1:${omniroutePort}${HEALTH.OMNIROUTE_PATH}`;
  const omnirouteOk = await healthCheckWithRetry(omnirouteUrl);

  return {
    smyth: smythOk,
    omniroute: omnirouteOk,
    smythUrl: `http://127.0.0.1:${PORTS.SMYTH}`,
    omnirouteUrl: `http://127.0.0.1:${omniroutePort}`,
  };
}

function stopAll() {
  return new Promise((resolve) => {
    let remaining = 0;
    const done = () => {
      remaining--;
      if (remaining <= 0) resolve();
    };

    const kill = (proc, name) => {
      if (!proc || proc.killed) return;
      remaining++;
      proc.kill('SIGTERM');
      const force = setTimeout(() => {
        if (!proc.killed) proc.kill('SIGKILL');
      }, SHUTDOWN.GRACEFUL_TIMEOUT_MS);
      proc.on('exit', () => {
        clearTimeout(force);
        done();
      });
    };

    kill(smythProcess, 'smyth');
    kill(omnirouteProcess, 'omniroute');

    if (remaining === 0) resolve();
  });
}

function getStatus() {
  return {
    smyth: smythProcess && !smythProcess.killed,
    omniroute: omnirouteProcess && !omnirouteProcess.killed,
    smythUrl: `http://127.0.0.1:${PORTS.SMYTH}`,
    omnirouteUrl: omniroutePort ? `http://127.0.0.1:${omniroutePort}` : null,
  };
}

function getOmniroutePort() {
  return omniroutePort;
}

module.exports = {
  startAll,
  stopAll,
  getStatus,
  getOmniroutePort,
  spawnSmyth,
  spawnOmniroute,
  healthCheckWithRetry,
};
