"use client";

// Central state for the Design Studio. One reducer, explicit actions — replaces
// the ~15 drifting useState calls the old panel used. All generation, iteration,
// selection, branching, overlay, and session actions flow through here.

import { useReducer, useCallback } from "react";
import type { DesignImage, DesignShape } from "@/lib/design-store";

export interface DesignChatMsg {
  id: string;
  role: "user" | "agent";
  content: string;
  imageId?: string;
  /** ids of images generated by this turn (agent messages) */
  imageIds?: string[];
  pending?: boolean;
  timestamp: number;
}

export interface DesignSettings {
  prompt: string;
  negativePrompt: string;
  shape: DesignShape;
  style: string;
  numImages: number;
  seed: number;
  guidanceScale: number;
}

export interface DesignState {
  sessionId: string | null;
  sessionName: string;
  pinned: boolean;
  images: DesignImage[];
  selectedImageId: string | null;
  chat: DesignChatMsg[];
  settings: DesignSettings;
  generating: boolean;
  generatingCount: number;
  assisting: boolean;
  streaming: boolean;
  error: string | null;
  compareId: string | null;
}

export const initialDesignState: DesignState = {
  sessionId: null,
  sessionName: "Untitled design",
  pinned: false,
  images: [],
  selectedImageId: null,
  chat: [],
  settings: {
    prompt: "",
    negativePrompt: "",
    shape: "square",
    style: "none",
    numImages: 1,
    seed: -1,
    guidanceScale: 7,
  },
  generating: false,
  generatingCount: 0,
  assisting: false,
  streaming: false,
  error: null,
  compareId: null,
};

export type DesignAction =
  | { type: "LOAD_SESSION"; payload: Partial<DesignState> }
  | { type: "SET_SETTINGS"; payload: Partial<DesignSettings> }
  | { type: "SET_NAME"; name: string }
  | { type: "SET_PINNED"; pinned: boolean }
  | { type: "GENERATE_START"; count: number }
  | { type: "GENERATE_SUCCESS"; images: DesignImage[]; prompt: string }
  | { type: "GENERATE_FAIL"; error: string }
  | { type: "SELECT_IMAGE"; id: string | null }
  | { type: "DELETE_IMAGE"; id: string }
  | { type: "SET_OVERLAY"; id: string; svg: string }
  | { type: "SET_HTML_OVERLAY"; id: string; html: string }
  | { type: "CHAT_ADD"; msg: DesignChatMsg }
  | { type: "CHAT_UPDATE"; id: string; patch: Partial<DesignChatMsg> }
  | { type: "SET_ASSISTING"; value: boolean }
  | { type: "SET_STREAMING"; value: boolean }
  | { type: "SET_ERROR"; error: string | null }
  | { type: "SET_COMPARE"; id: string | null }
  | { type: "RESET" };

let mid = 0;
const nextId = () => `dm-${Date.now()}-${++mid}`;

function reducer(state: DesignState, action: DesignAction): DesignState {
  switch (action.type) {
    case "LOAD_SESSION":
      return { ...state, ...action.payload };
    case "SET_SETTINGS":
      return { ...state, settings: { ...state.settings, ...action.payload } };
    case "SET_NAME":
      return { ...state, sessionName: action.name };
    case "SET_PINNED":
      return { ...state, pinned: action.pinned };
    case "GENERATE_START":
      return {
        ...state,
        generating: true,
        generatingCount: action.count,
        error: null,
      };
    case "GENERATE_SUCCESS": {
      const images = [...action.images, ...state.images];
      const selectedImageId = action.images[0]?.id ?? state.selectedImageId;
      return {
        ...state,
        images,
        selectedImageId,
        generating: false,
        generatingCount: 0,
      };
    }
    case "GENERATE_FAIL":
      return {
        ...state,
        generating: false,
        generatingCount: 0,
        error: action.error,
      };
    case "SELECT_IMAGE":
      return { ...state, selectedImageId: action.id, compareId: null };
    case "DELETE_IMAGE": {
      const images = state.images.filter((i) => i.id !== action.id);
      const selectedImageId =
        state.selectedImageId === action.id
          ? images[0]?.id ?? null
          : state.selectedImageId;
      return { ...state, images, selectedImageId };
    }
    case "SET_OVERLAY":
      return {
        ...state,
        images: state.images.map((i) =>
          i.id === action.id ? { ...i, overlaySvg: action.svg } : i
        ),
      };
    case "SET_HTML_OVERLAY":
      return {
        ...state,
        images: state.images.map((i) =>
          i.id === action.id ? { ...i, overlayHtml: action.html } : i
        ),
      };
    case "CHAT_ADD":
      return { ...state, chat: [...state.chat, action.msg] };
    case "CHAT_UPDATE":
      return {
        ...state,
        chat: state.chat.map((m) =>
          m.id === action.id ? { ...m, ...action.patch } : m
        ),
      };
    case "SET_ASSISTING":
      return { ...state, assisting: action.value };
    case "SET_STREAMING":
      return { ...state, streaming: action.value };
    case "SET_ERROR":
      return { ...state, error: action.error };
    case "SET_COMPARE":
      return { ...state, compareId: action.id };
    case "RESET":
      return { ...initialDesignState, settings: { ...state.settings } };
    default:
      return state;
  }
}

export function makeMsg(
  role: "user" | "agent",
  content: string,
  extra?: Partial<DesignChatMsg>
): DesignChatMsg {
  return { id: nextId(), role, content, timestamp: Date.now(), ...extra };
}

export function useDesignSession() {
  const [state, dispatch] = useReducer(reducer, initialDesignState);

  const selectedImage =
    state.images.find((i) => i.id === state.selectedImageId) ?? null;

  // The filmstrip: versions of the currently-selected lineage branch, newest last.
  // We walk up from the selected image to its root, then collect that whole chain.
  const filmstrip = useCallback((): DesignImage[] => {
    if (!selectedImage) return state.images.slice(0, 12);
    const byId = new Map(state.images.map((i) => [i.id, i]));
    // walk to root
    let root = selectedImage;
    let guard = 0;
    while (root.parentId && byId.get(root.parentId) && guard++ < 200) {
      root = byId.get(root.parentId)!;
    }
    // BFS down collecting the branch that contains the selection
    const chain: DesignImage[] = [];
    const walk = (img: DesignImage) => {
      chain.push(img);
      const children = state.images.filter((c) => c.parentId === img.id);
      // prefer the child path that leads toward the current selection
      const toward = children.find((c) => isAncestor(c, selectedImage, byId));
      const next = toward ?? children[children.length - 1];
      if (next) walk(next);
    };
    walk(root);
    return chain;
  }, [state.images, selectedImage]);

  return { state, dispatch, selectedImage, filmstrip };
}

function isAncestor(
  maybeAncestor: DesignImage,
  img: DesignImage,
  byId: Map<string, DesignImage>
): boolean {
  let cur: DesignImage | undefined = img;
  let guard = 0;
  while (cur && guard++ < 200) {
    if (cur.id === maybeAncestor.id) return true;
    cur = cur.parentId ? byId.get(cur.parentId) : undefined;
  }
  return false;
}
