#!/usr/bin/env node
/**
 * manifest-sync.mjs — Phase 1 (option B): regenerate the integration portion
 * of mcp-servers.yaml from smyth-manifest.yaml.
 *
 * USAGE:
 *   node scripts/manifest-sync.mjs            # write mcp-servers.yaml
 *   node scripts/manifest-sync.mjs --dry-run  # show what would change, write nothing
 *
 * DESIGN (option B — manual sync, not auto-generate on boot):
 *   - smyth-manifest.yaml is canonical for BUSINESS INTEGRATIONS (crm, calendar,
 *     email, design, ...).
 *   - mcp-servers.yaml ALSO contains CORE TOOLING servers (filesystem, memory,
 *     sequential-thinking, brave-search, github, postgres, puppeteer, macos,
 *     velorn, openpencil, ...) that are platform defaults, NOT per-client
 *     integrations.
 *
 *   Therefore this script does a MERGE/UPSERT, NOT a full regeneration:
 *     - Every integration in the manifest that has an `mcp` block gets a
 *       matching server entry in mcp-servers.yaml (created or updated).
 *     - Every other server in mcp-servers.yaml is left UNTOUCHED.
 *     - Integrations in the manifest with status "failed" or no mcp block are
 *       skipped (they don't produce a server).
 *
 * SECURITY:
 *   - The manifest references secrets by envKey (the NAME), never the value.
 *   - This script renders that envKey as an env placeholder `${KEY}` in the
 *     generated YAML, matching the existing mcp-servers.yaml convention.
 *
 * No dependencies beyond js-yaml (already a project runtime dep) and node:fs.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { load as loadYaml, dump as dumpYaml } from "js-yaml";

const ROOT = process.cwd();
const MANIFEST_PATH = join(ROOT, "smyth-manifest.yaml");
const YAML_PATH = join(ROOT, "mcp-servers.yaml");
const DRY_RUN = process.argv.includes("--dry-run");

// ── Helpers ──────────────────────────────────────────────────────────────

function buildStdioServer(it) {
  return {
    description: `${it.name} (integration: ${it.key})`,
    transport: it.mcp.transport || "stdio",
    command: it.mcp.command,
    args: it.mcp.args || [],
    env: it.mcp.envKey ? { [it.mcp.envKey]: `\${${it.mcp.envKey}}` } : undefined,
    enabled: it.status === "migrated" || it.status === "migrating",
  };
}

function buildHttpServer(it) {
  const srv = {
    description: `${it.name} (integration: ${it.key})`,
    transport: it.mcp.transport || "http",
    url: it.mcp.url,
    enabled: it.status === "migrated" || it.status === "migrating",
  };
  // auth: bearer → Authorization header with env placeholder; api-key → same pattern
  if (it.mcp.auth === "bearer" && it.mcp.envKey) {
    srv.headers = { Authorization: `Bearer \${${it.mcp.envKey}}` };
  } else if (it.mcp.auth === "api-key" && it.mcp.envKey) {
    srv.headers = { "X-API-Key": `\${${it.mcp.envKey}}` };
  }
  return srv;
}

function serverForIntegration(it) {
  if (!it.mcp) return null;
  if (it.status === "failed") return null;
  if (it.mcp.transport === "stdio") return buildStdioServer(it);
  if (it.mcp.transport === "http" || it.mcp.transport === "sse") return buildHttpServer(it);
  return null;
}

// ── Main ─────────────────────────────────────────────────────────────────

function main() {
  if (!existsSync(MANIFEST_PATH)) {
    console.error("✗ No smyth-manifest.yaml found. Create one first (see smyth-manifest.template.yaml).");
    process.exit(1);
  }

  const manifest = loadYaml(readFileSync(MANIFEST_PATH, "utf-8"));
  const integrations = manifest.integrations || [];

  // Load existing YAML (or start empty)
  let existing = { servers: {} };
  if (existsSync(YAML_PATH)) {
    const parsed = loadYaml(readFileSync(YAML_PATH, "utf-8")) || {};
    existing = { servers: parsed.servers || {} };
  }

  const changes = [];
  const next = { ...existing };

  for (const it of integrations) {
    const srv = serverForIntegration(it);
    if (!srv) {
      changes.push(`  skip      ${it.key} (status=${it.status}, no mcp block or failed)`);
      continue;
    }
    const existed = Boolean(existing.servers[it.key]);
    next.servers[it.key] = srv;
    changes.push(`  ${existed ? "update" : "create "}  ${it.key} → ${srv.transport} ${srv.url || srv.command || ""} (enabled=${srv.enabled})`);
  }

  // Build output — wrap servers, preserve nothing else (YAML only has servers)
  const outYaml = dumpYaml({ servers: next.servers }, { lineWidth: 100, noRefs: true });

  if (DRY_RUN) {
    console.log("DRY RUN — no files written. Changes:\n" + changes.join("\n"));
    process.exit(0);
  }

  const header = `# mcp-servers.yaml — GENERATED by scripts/manifest-sync.mjs\n# Source of truth: smyth-manifest.yaml (business integrations).\n# Core tooling servers (filesystem, memory, macos, etc.) are preserved from prior file.\n# Regenerated ${new Date().toISOString()}\n\n`;
  writeFileSync(YAML_PATH, header + outYaml, "utf-8");

  console.log("✓ mcp-servers.yaml regenerated.\n" + changes.join("\n"));
}

main();
